In [2]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, plot_tree
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [3]:
def filter_bad_data(df, col, filters, removeNaN):
    df_c = df.copy()
    df_f = df_c
    for filter in filters:
        df_f = df_f[df_f[col]!=filter]
    if removeNaN:
        df_f = df_f[pd.isna(df_f[col]) == False]
    return df_f

In [30]:
#data read in
res_df = pd.read_csv("real_estate_sales.csv")

target_col_names = ["OBJECTID", "SalePrice", "TotalAppraisedValue"]
feat_col_names = ["OBJECTID", "xrCompositeLandUseID", "xrBuildingTypeID", "xrPrimaryNeighborhoodID", "LandSF", "SaleDate", "AssrLandUse"]

res_df_filtered = filter_bad_data(res_df, "SalePrice", [0, 1], True)
target_df = res_df_filtered[target_col_names].copy()
feat_df = res_df_filtered[feat_col_names].copy()

object_id = target_df["OBJECTID"].copy()
sp = target_df["SalePrice"].copy()
tav = target_df["TotalAppraisedValue"].copy()
price_ratio = sp/tav
target_data_dict = {"ObjectID": object_id,
                    "SalePrice": sp,
                    "AppraisedValue": tav,
                    "PriceRatio": price_ratio}
target_data_df = pd.DataFrame(target_data_dict)
target_data_df.head()


,ObjectID,SalePrice,AppraisedValue,PriceRatio
0,1,259000.0,187200,1.383547
1,2,208000.0,192300,1.081643
2,3,125000.0,148400,0.842318
4,5,177000.0,197900,0.894391
6,7,188000.0,170700,1.101347


In [46]:
target_data_df["PriceRatio"].max()
print(target_data_df.size)
pr = target_data_df[target_data_df["PriceRatio"]<10000].copy()
print(pr.size)
pr = pr["PriceRatio"]
print(pr.max())
pr = np.array(pr)
#plt.hist(target_data_df["PriceRatio"], bins=20)
i = np.where(pr == pr.max())

av = np.array(target_data_df["AppraisedValue"])
sale = np.array(target_data_df["SalePrice"])

print(pr[i])
print(av[i])
print(sale[i])

18408
18400
1905.7762057877815
[1905.77620579 1905.77620579 1905.77620579]
[31100 31100 31100]
[59269640. 59269640. 59269640.]


In [ ]:
#res_df_filtered.head()
#feat_df.head()
#target_df.head()